language: minimal

services:
  - docker

before_install:
  - docker -v && docker-compose -v

script: ./build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(development|master)$
